language: R
sudo: false
cache: packages
dist: trusty
warnings_are_errors: false
after_success:
- Rscript -e 'covr::codecov()'
env:
  global:
  - secure: NQo6ytmtkvnRVxNk25e10n4xXHXt6AOuWmItR2+G5eABwfOOSIIRJriyYiNWlwAbUfbhRCJD+q9BnJycxjt7Nk+lTN3kPmk/SnCmIqJABIvCQr0Te20IQBdMbJjFr0gCculN4bF9D9h8Xasf4VD7G+4+YVAs1rSOKN6YiG966VuY6QQdcRKemfXmzWn7Akm+WAfySLmzzorwVxUNWwROUwPRttHUu7lM0qJVRpJbPdVA/ZTENBX8ONMI1gmQ5bXi7t47U46C41V9P3bc3oNmJGee7V3mO8LzUguOwOIMIOMnLR9luzoAxokbzuEDbNYnA67j/AGEZP5/OE7Nu8sduk+WP9Dj6h4pHEk+Jz2U8wt6/c+1WjUSatrNskaScj0zncWZMUXOTMZcs/mlwYzA1a93207RG3qunthu3S7XuCujwRSRcTHccXQS0x4Fr61zQ9xo/LEyhQYfacz98KlQ1PjslJBXTiUkGkBuGDztPeDho6iciFoiF5JlRJNoL6Of1soGUc39Un4MAY4DEFMMz4Ll1JHWkW7Hd5dJSxKF6RQVcA8kqEX3FtLQdT+ZlWn2g7RCUh1x5TClZk0+8RS4N6K3DqUFAY49jg+HTCQgo2RzhR5/n61U0rDIWr1iQD/xssppr48GEhCLTbE6eSDY07zV6Xhiw+HggojOTLNL5XE=
